### ISSUE TITLE
"No server available" after scale down

### ISSUE THREAD

**Issue by skwasiborski** [aspnet/AzureSignalR-samples#20]
When I use Azure SignalR Service and scale out my backend everything works as expected and my clients are distributed among the backends. When I scale down (decrease the number of replicas) I start getting No server available on the clients i.e. {"type":7,"error":"No server available."} on the WebSocket connection after first attempt to invoke hub method. The problem occurs only for some clients. If I rescale to previous number of replicas everything starts to work correctly.

Given the scaled out number of replicas is 10 and scaled down is 1 the problem is quite severe i.e. I get the error most of the time.

The issue can be reproduced with following docker-compose.yml. localhost:5000/chatroom is the image of the sample chatroom build into container using the provided Dockerfile. 

```
version: '3'

services:
  backend: 
    image: localhost:5000/chatroom
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
```

Repro steps: 
1. Run docker-compose up --scale backend=10
2. Connect some clients.
3. Run docker-compose up --scale backend=1

This compose file will run multiple instances of the chat sample and a HAProxy in front for load balancing. The dockercloud version of HAProxy will auto configure to forward to all containers in the same compose file.
